/** Product name — use in titles and `openGraph.siteName`. */
export const SITE_BRAND_NAME = "Family Relocation Engine";

/** Sitewide default: root layout `description`, homepage, JSON-LD `WebSite.description`. */
export const SITE_DESCRIPTION =
  "Family relocation guides for parents — compare cities on visas, international schools, childcare, safety, and monthly costs before you move.";

/** Homepage only: same string for `<title>`, `og:title`, and `twitter:title`. */
export const SITE_HOME_TITLE =
  `Family Relocation Guide: Visas, Schools & Childcare | ${SITE_BRAND_NAME}`;

/** `/destinations` index — shared title + description for meta / OG / Twitter. */
export const SITE_DESTINATIONS_TITLE = `All Destinations — ${SITE_BRAND_NAME}`;

export const SITE_DESTINATIONS_DESCRIPTION =
  "Browse every family-friendly city in our database — visa rules, schools, childcare costs, and safety scores.";

/**
 * Homepage social preview: generated by `app/opengraph-image.tsx` (text + `public/og-home.png` background).
 * `?v=` cache-busts Facebook/LinkedIn when the design changes.
 */
export const SITE_HOME_OG_IMAGE = "/opengraph-image?v=5";

/** Alt text for the generated OG image (`export const alt` in `opengraph-image.tsx`). */
export const SITE_HOME_OG_IMAGE_ALT =
  "Hero headline on a coastal photo: plan your family's move — visas, schools, and real costs in one place";

/**
 * `/destinations` social preview — `app/destinations/opengraph-image.tsx`.
 * Bump `?v` when the graphic changes.
 */
export const SITE_DESTINATIONS_OG_IMAGE = "/destinations/opengraph-image?v=1";

export const SITE_DESTINATIONS_OG_IMAGE_ALT =
  "Browse all family relocation city guides — visas, schools, childcare, and safety";
