import { clipMetaDescription } from "@/lib/seo/description";

/** Product name — use in titles and `openGraph.siteName`. */
export const SITE_BRAND_NAME = "Family Relocation Engine";

/**
 * Brand suffix for `<title>` on country, city, and /destinations pages (≤70 chars total).
 * Homepage keeps full `SITE_BRAND_NAME` unless explicitly updated.
 */
export const SITE_SERP_TITLE_BRAND = "FamiRelo";

/** Sitewide default: root layout `description`, homepage, JSON-LD `WebSite.description`. */
export const SITE_DESCRIPTION = clipMetaDescription(
  "Move abroad with kids: visa options, international schools, childcare, rent, and safety — compare cities with clear, family-first relocation guides.",
);

/** Homepage `<title>` / default meta (intent + keywords + brand). */
export const SITE_HOME_TITLE = `Family Relocation: Visas, Schools & Costs Before You Move | ${SITE_BRAND_NAME}`;

/** Shorter headline for OG/Twitter when the full title is long. */
export const SITE_HOME_OPEN_GRAPH_TITLE = `Family relocation: visas, schools & childcare | ${SITE_BRAND_NAME}`;

/** `/destinations` — same string for `<title>` and Open Graph / Twitter title (see `buildPageMetadata`). */
export const SITE_DESTINATIONS_TITLE = `Browse family relocation guides by city | ${SITE_SERP_TITLE_BRAND}`;

export const SITE_DESTINATIONS_DESCRIPTION = clipMetaDescription(
  "Family relocation guides by city: visas, schools, childcare, housing and healthcare for parents with kids. Browse and compare every destination in one place.",
);

/**
 * Homepage social preview: generated by `app/opengraph-image.tsx` (text + `public/og-home.png` background).
 * `?v=` cache-busts Facebook/LinkedIn when the design changes.
 */
export const SITE_HOME_OG_IMAGE = "/opengraph-image?v=5";

/** Alt text for the generated OG image (`export const alt` in `opengraph-image.tsx`). */
export const SITE_HOME_OG_IMAGE_ALT =
  "Hero headline on a coastal photo: plan your family's move — visas, schools, and real costs in one place";

/**
 * `/destinations` social preview — `app/destinations/opengraph-image.tsx`.
 * Bump `?v` when the graphic changes.
 */
export const SITE_DESTINATIONS_OG_IMAGE = "/destinations/opengraph-image?v=1";

export const SITE_DESTINATIONS_OG_IMAGE_ALT =
  "Browse all family relocation city guides — visas, schools, childcare, and safety";

/**
 * `/compare` (premium feature landing) — same string for `<title>` and OG/Twitter title.
 * Keep < 70 chars (incl. ` | FamiRelo`).
 */
export const SITE_COMPARE_TITLE = `Compare cities side by side for family relocation | ${SITE_SERP_TITLE_BRAND}`;

export const SITE_COMPARE_OPEN_GRAPH_TITLE = SITE_COMPARE_TITLE;

export const SITE_COMPARE_DESCRIPTION = clipMetaDescription(
  "Pick up to 3 cities and get a personalised report scored to your budget, family size, and priorities. Match scores, schools, visas — one report, yours forever.",
);

/** `/compare` social preview — generated by `app/compare/opengraph-image.tsx`. Bump `?v` when the design changes. */
export const SITE_COMPARE_OG_IMAGE = "/compare/opengraph-image?v=1";

export const SITE_COMPARE_OG_IMAGE_ALT =
  "Compare cities side by side: personalised match scores, budget fit, schools and visas for your family relocation";
