import { clipMetaDescription } from "@/lib/seo/description";

/** Product name — use in titles and `openGraph.siteName`. */
export const SITE_BRAND_NAME = "Family Relocation Engine";

/** Sitewide default: root layout `description`, homepage, JSON-LD `WebSite.description`. */
export const SITE_DESCRIPTION = clipMetaDescription(
  "Move abroad with kids: visa options, international schools, childcare, rent, and safety — compare cities with clear, family-first relocation guides.",
);

/** Homepage `<title>` / default meta (intent + keywords + brand). */
export const SITE_HOME_TITLE = `Family Relocation: Visas, Schools & Costs Before You Move | ${SITE_BRAND_NAME}`;

/** Shorter headline for OG/Twitter when the full title is long. */
export const SITE_HOME_OPEN_GRAPH_TITLE = `Family relocation: visas, schools & childcare | ${SITE_BRAND_NAME}`;

/** `/destinations` — SERP title + meta (discovery + benefit). */
export const SITE_DESTINATIONS_TITLE = `Browse Family Relocation Guides by City | ${SITE_BRAND_NAME}`;

export const SITE_DESTINATIONS_OPEN_GRAPH_TITLE = `All cities — visas, schools & family costs | ${SITE_BRAND_NAME}`;

export const SITE_DESTINATIONS_DESCRIPTION = clipMetaDescription(
  "Family relocation guides by city: visas, schools, childcare, rent & safety for parents moving with kids. Browse every destination in one place.",
);

/**
 * Homepage social preview: generated by `app/opengraph-image.tsx` (text + `public/og-home.png` background).
 * `?v=` cache-busts Facebook/LinkedIn when the design changes.
 */
export const SITE_HOME_OG_IMAGE = "/opengraph-image?v=5";

/** Alt text for the generated OG image (`export const alt` in `opengraph-image.tsx`). */
export const SITE_HOME_OG_IMAGE_ALT =
  "Hero headline on a coastal photo: plan your family's move — visas, schools, and real costs in one place";

/**
 * `/destinations` social preview — `app/destinations/opengraph-image.tsx`.
 * Bump `?v` when the graphic changes.
 */
export const SITE_DESTINATIONS_OG_IMAGE = "/destinations/opengraph-image?v=1";

export const SITE_DESTINATIONS_OG_IMAGE_ALT =
  "Browse all family relocation city guides — visas, schools, childcare, and safety";
